<?php

return [
    'items' => [
        [
            'id' => 'people.attendance',
            'label' => 'Attendance',
            'icon' => 'heroicon-o-clock',
            'parent' => 'people',
        ],
        [
            'id' => 'people.attendance.my',
            'label' => 'My Attendance',
            'icon' => 'heroicon-o-calendar-days',
            'route' => 'people.attendance.index',
            'permission' => 'people.attendance.view',
            'parent' => 'people.attendance',
        ],
        [
            'id' => 'people.attendance.approvals',
            'label' => 'Approvals',
            'icon' => 'heroicon-o-check-badge',
            'route' => 'people.attendance.approvals',
            'permission' => 'people.attendance.approve',
            'parent' => 'people.attendance',
        ],
        [
            'id' => 'people.attendance.operations',
            'label' => 'Attendance Operations',
            'icon' => 'heroicon-o-clipboard-document-list',
            'route' => 'people.attendance.operations',
            'permission' => 'people.attendance.manage',
            'parent' => 'people.attendance',
        ],
        [
            'id' => 'people.attendance.policy-studio',
            'label' => 'Policy Studio',
            'icon' => 'heroicon-o-adjustments-horizontal',
            'permission' => 'people.attendance.manage',
            'parent' => 'people.attendance',
        ],
        [
            'id' => 'people.attendance.policy-studio.library',
            'label' => 'Policy Library',
            'icon' => 'heroicon-o-rectangle-stack',
            'route' => 'people.attendance.policy-studio.library',
            'permission' => 'people.attendance.manage',
            'parent' => 'people.attendance.policy-studio',
        ],
        [
            'id' => 'people.attendance.policy-studio.builder',
            'label' => 'Policy Builder',
            'icon' => 'heroicon-o-wrench-screwdriver',
            'route' => 'people.attendance.policy-studio.builder',
            'permission' => 'people.attendance.manage',
            'parent' => 'people.attendance.policy-studio',
        ],
        [
            'id' => 'people.attendance.policy-studio.validator',
            'label' => 'Policy Validator',
            'icon' => 'heroicon-o-shield-check',
            'route' => 'people.attendance.policy-studio.validator',
            'permission' => 'people.attendance.manage',
            'parent' => 'people.attendance.policy-studio',
        ],
        [
            'id' => 'people.attendance.shifts',
            'label' => 'Shift Builder',
            'icon' => 'heroicon-o-clock',
            'route' => 'people.attendance.shifts',
            'permission' => 'people.attendance.manage',
            'parent' => 'people.attendance.policy-studio',
        ],
        [
            'id' => 'people.attendance.allowance-rules',
            'label' => 'Allowance Rules',
            'icon' => 'heroicon-o-banknotes',
            'route' => 'people.attendance.allowance-rules',
            'permission' => 'people.attendance.manage',
            'parent' => 'people.attendance.policy-studio',
        ],
        [
            'id' => 'people.attendance.rosters',
            'label' => 'Roster Builder',
            'icon' => 'heroicon-o-calendar-days',
            'route' => 'people.attendance.rosters',
            'permission' => 'people.attendance.manage',
            'parent' => 'people.attendance',
        ],
        [
            'id' => 'people.attendance.clocking-locations',
            'label' => 'Clocking Locations',
            'icon' => 'heroicon-o-map-pin',
            'route' => 'people.attendance.clocking-locations',
            'permission' => 'people.attendance.manage',
            'parent' => 'people.attendance',
        ],
    ],
];
