<?php

use App\Base\Authz\Enums\PrincipalType;
use App\Base\Authz\Models\PrincipalRole;
use App\Base\Authz\Models\Role;
use App\Base\Media\Models\MediaAsset;
use App\Base\Tenancy\Contracts\TenantContext;
use App\Core\AI\Services\Browser\PlaywrightRunner;
use App\Core\Company\Models\Company;
use App\Core\Company\Models\Department;
use App\Core\Company\Models\DepartmentType;
use App\Core\Employee\Models\Employee;
use App\Core\User\Models\User;
use App\Domains\People\Employees\Livewire\TrainingPassport;
use App\Domains\People\Provider\Data\ExternalReference;
use App\Domains\People\Provider\Data\WorkforceSubject;
use App\Domains\People\Provider\Enums\WorkforceResourceType;
use App\Domains\People\Settings\Models\EmployeePortalAccess;
use App\Domains\People\Settings\Models\EmployeeWorkProfile;
use App\Domains\People\Settings\Models\PeopleReferenceEntry;
use App\Domains\People\Skills\Data\SkillDraft;
use App\Domains\People\Skills\Database\Seeders\RequirementProfileWorkflowSeeder;
use App\Domains\People\Skills\Models\EmployeeSkillScore;
use App\Domains\People\Skills\Models\SkillActorBinding;
use App\Domains\People\Skills\Models\SkillAssessment;
use App\Domains\People\Skills\Services\SkillCatalogStore;
use App\Domains\People\Training\Data\TrainingCourseDraft;
use App\Domains\People\Training\Data\TrainingEventDraft;
use App\Domains\People\Training\Enums\AttendanceStatus;
use App\Domains\People\Training\Enums\DeliveryMode;
use App\Domains\People\Training\Exceptions\TrainingPassportDenied;
use App\Domains\People\Training\Livewire\HrGovernance\Index as HrGovernanceIndex;
use App\Domains\People\Training\Models\TrainingParticipant;
use App\Domains\People\Training\Models\TrainingParticipationFact;
use App\Domains\People\Training\Models\TrainingPassportDocument;
use App\Domains\People\Training\Models\TrainingPassportDocumentAudit;
use App\Domains\People\Training\Models\TrainingSession;
use App\Domains\People\Training\Services\TrainingCatalogStore;
use App\Domains\People\Training\Services\TrainingEventStore;
use App\Domains\People\Training\Services\TrainingPassportDocumentStore;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Testing\TestResponse;
use Livewire\Features\SupportLockedProperties\CannotUpdateLockedPropertyException;
use Livewire\Livewire;

/**
 * Printable training passport (0014-a): a stored, audited PDF generated by
 * the employee from their passport page or by HR from the HR queue, and
 * downloadable only by that employee or HR of the company.
 *
 * The platform renderer drives Chromium through PlaywrightRunner; here the
 * runner is a stub that writes the rendered HTML as the "PDF" bytes, so the
 * text the renderer would print is what the stored document contains and
 * the assertions read it back from the stored file.
 */
afterEach(function (): void {
    app(TenantContext::class)->clear();
    Carbon::setTestNow();
});

beforeEach(function (): void {
    $this->withoutVite();
    Storage::fake('local');
    config()->set('pdf.disk', 'local');
    config()->set('pdf.artifact_directory', 'pdf-artifacts');
    app()->instance(PlaywrightRunner::class, new class extends PlaywrightRunner
    {
        public function execute(string $action, array $arguments = []): array
        {
            file_put_contents((string) $arguments['output_path'], "%PDF-1.4 stub\n".$arguments['html']);

            return ['ok' => true, 'action' => $action];
        }
    });
});

/**
 * @return array{
 *   tenantId: int, company: Company, user: User, employee: Employee, otherUser: User, other: Employee,
 *   hr: User, hod: User, head: Employee, member: Employee, siblingHr: User, siblingEmployee: Employee, skillName: string
 * }
 */
function tpdFixture(): array
{
    [$tenant, $company] = createTenantWithCompany(['name' => 'Passport document tenant']);
    $tenantId = (int) $tenant->id;
    app(TenantContext::class)->set($tenantId);
    setupAuthzRoles();
    (new RequirementProfileWorkflowSeeder)->run();

    $unit = PeopleReferenceEntry::query()->create([
        'company_id' => $company->id, 'type' => PeopleReferenceEntry::TYPE_ORGANIZATION_UNIT,
        'code' => 'tpd-ops', 'name' => 'Passport document operations', 'status' => PeopleReferenceEntry::STATUS_ACTIVE,
    ]);
    $type = DepartmentType::query()->create(['code' => 'tpd-ops', 'name' => 'Passport document ops', 'category' => 'operational', 'is_active' => true]);
    $department = Department::query()->create(['company_id' => $company->id, 'department_type_id' => $type->id, 'status' => 'active']);

    $employee = tpdEmployee((int) $company->id, $department, $unit, 'Passport Own');
    $other = tpdEmployee((int) $company->id, $department, $unit, 'Passport Other');
    $head = tpdEmployee((int) $company->id, $department, $unit, 'Passport Head');
    $member = tpdEmployee((int) $company->id, $department, $unit, 'Passport Member');
    $department->update(['head_id' => $head->id]);
    $member->update(['supervisor_id' => $head->id]);

    $user = tpdUser($tenantId, $company, $employee, 'people_employee');
    $otherUser = tpdUser($tenantId, $company, $other, 'people_employee');
    $hod = tpdUser($tenantId, $company, $head, 'people_hod');
    $hr = tpdUser($tenantId, $company, null, 'people_hr');

    $skillName = tpdTraining($tenantId, (int) $company->id, $employee, 'Own training', 'Own skill', 'CERT-OWN-EXPIRED', now()->subDay(), $user);
    tpdTraining($tenantId, (int) $company->id, $employee, 'Own current training', 'Own current skill', 'CERT-OWN-CURRENT', now()->addYear(), $user);
    tpdTraining($tenantId, (int) $company->id, $other, 'Other training', 'Other skill', 'CERT-OTHER', now()->addYear(), $otherUser);
    tpdTraining($tenantId, (int) $company->id, $member, 'Member training', 'Member skill', 'CERT-MEMBER', now()->addYear(), $hod);

    $sibling = Company::factory()->create(['tenant_id' => $tenantId, 'name' => 'Passport sibling company', 'status' => 'active']);
    $siblingEmployee = Employee::factory()->create(['company_id' => $sibling->id, 'full_name' => 'Passport Sibling', 'status' => 'active']);
    $siblingHr = tpdUser($tenantId, $sibling, null, 'people_hr');

    return compact('tenantId', 'company', 'user', 'employee', 'otherUser', 'other', 'hr', 'hod', 'head', 'member', 'siblingHr', 'siblingEmployee', 'skillName');
}

function tpdEmployee(int $companyId, Department $department, PeopleReferenceEntry $unit, string $name): Employee
{
    $employee = Employee::factory()->create([
        'company_id' => $companyId, 'department_id' => $department->id,
        'full_name' => $name, 'short_name' => null, 'status' => 'active',
    ]);
    EmployeeWorkProfile::query()->create(['employee_id' => $employee->id, 'organization_unit_id' => $unit->id]);

    return $employee;
}

function tpdUser(int $tenantId, Company $company, ?Employee $employee, string $roleCode): User
{
    $user = User::factory()->create(['company_id' => $company->id, 'employee_id' => $employee?->id]);
    PrincipalRole::query()->create([
        'company_id' => $company->id, 'principal_type' => PrincipalType::USER->value,
        'principal_id' => $user->id,
        'role_id' => Role::query()->whereNull('company_id')->where('code', $roleCode)->sole()->id,
    ]);
    if ($employee !== null) {
        EmployeePortalAccess::query()->create([
            'employee_id' => $employee->id, 'user_id' => $user->id,
            'display_name' => $employee->full_name, 'status' => EmployeePortalAccess::STATUS_ACTIVE,
        ]);
        SkillActorBinding::query()->create([
            'tenant_id' => $tenantId, 'company_entity_id' => $company->id,
            'platform_user_id' => $user->id, 'employee_entity_id' => $employee->id,
            'user_entity_id' => $user->id, 'confirmed_by_user_id' => $user->id,
            'review_reference' => 'tpd-fixture', 'confirmed_at' => now(),
        ]);
    }

    return $user;
}

/** Records one attended event with a certificate and returns the mapped skill's name. */
function tpdTraining(
    int $tenantId,
    int $companyId,
    Employee $employee,
    string $title,
    string $skillName,
    string $certificate,
    Carbon $validUntil,
    User $recordedBy,
): string {
    $tag = Str::lower(Str::random(12));
    $catalog = app(SkillCatalogStore::class);
    $category = $catalog->defineCategory($companyId, "tpd-{$tag}", 'Passport document');
    $skill = $catalog->defineSkill($companyId, new SkillDraft(
        code: "tpd.{$tag}", name: $skillName, definition: 'A passport document test skill.', categoryId: (int) $category->id,
    ));
    $course = app(TrainingCatalogStore::class)->defineCourse($companyId, new TrainingCourseDraft(
        code: "tpd.{$tag}.course", title: $title, deliveryMode: DeliveryMode::InternalClassroom,
        skillIds: [(int) $skill->id], internalTrainerEmployeeEntityId: (int) $employee->id,
    ));
    $event = app(TrainingEventStore::class)->schedule($companyId, new TrainingEventDraft(
        courseId: (int) $course->id, startsAt: now()->addDay(), endsAt: now()->addDay()->addHours(4),
        capacity: 10, organizerEmployeeEntityId: (int) $employee->id,
    ));
    $participant = TrainingParticipant::query()->create([
        'tenant_id' => $tenantId, 'company_entity_id' => $companyId, 'event_id' => $event->id,
        'provider_id' => ExternalReference::PROVIDER_ID, 'employee_subject_id' => (string) $employee->id,
        'workforce_observed_at' => now(),
    ]);
    $session = TrainingSession::query()->create([
        'tenant_id' => $tenantId, 'company_entity_id' => $companyId, 'event_id' => $event->id,
        'session_reference' => "tpd-session-{$tag}", 'starts_at' => $event->starts_at, 'ends_at' => $event->ends_at,
        'created_by_user_id' => $recordedBy->id,
    ]);
    TrainingParticipationFact::query()->create([
        'tenant_id' => $tenantId, 'company_entity_id' => $companyId, 'event_id' => $event->id,
        'participant_id' => $participant->id, 'session_id' => $session->id,
        'attendance' => AttendanceStatus::Present, 'actual_minutes' => 120, 'pre_test' => null, 'post_test' => null,
        'certificate_reference' => $certificate,
        'certificate_valid_from' => now()->subYear()->toDateString(),
        'certificate_valid_until' => $validUntil->toDateString(),
        'evidence_references' => [], 'source' => 'fixture', 'source_reference' => "tpd-fact-{$tag}",
        'recorded_by_user_id' => $recordedBy->id, 'recorded_capability' => 'people.training.participation.manage',
        'recorded_at' => now(), 'confirmed_by_user_id' => $recordedBy->id,
        'confirmed_capability' => 'people.training.participation.verify', 'confirmed_at' => now(),
    ]);

    // The canonical score projection carries the employee's current level for
    // this skill; a draft source row satisfies its foreign key without the
    // assessment workflow, which is private to the Skills store.
    $assessment = SkillAssessment::query()->create([
        'tenant_id' => $tenantId, 'company_entity_id' => $companyId, 'employee_entity_id' => $employee->id,
        'skill_id' => $skill->id, 'requirement_reference' => "tpd.{$tag}.profile", 'requirement_version' => 1,
        'required_level' => 4, 'assessed_level' => 3, 'gap' => 1, 'criticality' => 'critical', 'mandatory_gate' => true,
        'method' => 'direct_observation', 'cycle' => 'annual', 'status' => 'draft',
        'evidence' => 'Observed.', 'assessed_at' => now()->subDay(), 'assessor_user_id' => $recordedBy->id,
    ]);
    EmployeeSkillScore::query()->create([
        'tenant_id' => $tenantId, 'company_entity_id' => $companyId, 'employee_entity_id' => $employee->id,
        'skill_id' => $skill->id, 'source_assessment_id' => (int) $assessment->id,
        'requirement_reference' => "tpd.{$tag}.profile", 'requirement_version' => 1,
        'required_level' => 4, 'current_level' => 3, 'gap' => 1, 'mandatory_gate' => true, 'criticality' => 'critical',
        'assessed_at' => now()->subDay(),
    ]);

    return $skillName;
}

function tpdSubject(int $tenantId, int $companyId, Employee $employee): WorkforceSubject
{
    return new WorkforceSubject($tenantId, $companyId, WorkforceResourceType::Employee, (string) $employee->id);
}

function tpdStoredText(TrainingPassportDocument $document): string
{
    $asset = $document->asset;
    expect($asset)->toBeInstanceOf(MediaAsset::class);

    return (string) Storage::disk($asset->disk)->get($asset->storage_key);
}

function tpdDownload(User $actor, int $documentId): TestResponse
{
    return test()->actingAs($actor)->get(route('people.training.passport.document', ['documentId' => $documentId]));
}

it('stores one document and one audit row whose PDF text carries the certificates, the expired marker, the watermark and the skill level', function (): void {
    // Freeze before the fixture: CERT-OWN-EXPIRED uses now()->subDay(), and
    // TrainingPassportReader marks expired with validUntil->isBefore(today()).
    // Freezing after the fixture made "yesterday" equal today once the wall
    // clock crossed the frozen date (postgres-mirror red on #409).
    Carbon::setTestNow('2026-09-07 10:30:00');
    $f = tpdFixture();

    Livewire::actingAs($f['user'])
        ->test(TrainingPassport::class)
        ->call('generatePassportPdf')
        ->assertHasNoErrors()
        ->assertDispatched('training-passport-generated');

    $documents = TrainingPassportDocument::query()->forCompany($f['tenantId'], (int) $f['company']->id)->get();
    expect($documents)->toHaveCount(1);
    $document = $documents->sole();
    expect($document->employee_entity_id)->toBe((int) $f['employee']->id)
        ->and($document->generated_by_user_id)->toBe((int) $f['user']->id)
        ->and($document->expires_at->toDateTimeString())->toBe('2026-10-07 10:30:00')
        ->and($document->template_version)->toBe(TrainingPassportDocumentStore::TEMPLATE_VERSION)
        ->and($document->asset?->mime_type)->toBe('application/pdf');

    $audits = TrainingPassportDocumentAudit::query()->forCompany($f['tenantId'], (int) $f['company']->id)->get();
    expect($audits)->toHaveCount(1)
        ->and($audits->sole()->event_type)->toBe(TrainingPassportDocument::EVENT_GENERATED)
        ->and($audits->sole()->actor_user_id)->toBe((int) $f['user']->id)
        ->and($audits->sole()->document_id)->toBe((int) $document->id);

    $text = tpdStoredText($document);
    expect($text)->toContain('CERT-OWN-EXPIRED')
        ->toContain('CERT-OWN-CURRENT')
        ->toContain('data-certificate-status="expired"')
        ->toContain('EXPIRED')
        ->toContain('Generated 2026-09-07 10:30 · Employee #'.$f['employee']->id)
        ->toContain($f['skillName'])
        ->toContain('Level 3')
        ->not->toContain('CERT-OTHER')
        ->not->toContain('CERT-MEMBER');
});

it('pins the subject to the authenticated employee whatever employee id the request supplies', function (): void {
    $f = tpdFixture();

    $page = Livewire::withQueryParams(['employee_id' => $f['other']->id, 'subjectId' => $f['other']->id])
        ->actingAs($f['user'])
        ->test(TrainingPassport::class);

    // A client-supplied subject is refused by the lock; were the lock gone,
    // the actor check behind it refuses to generate for anyone else.
    try {
        $page->set('subjectId', (string) $f['other']->id);
    } catch (CannotUpdateLockedPropertyException) {
    }

    $page->call('generatePassportPdf')->assertHasNoErrors();

    $document = TrainingPassportDocument::query()->forCompany($f['tenantId'], (int) $f['company']->id)->sole();
    expect($document->employee_entity_id)->toBe((int) $f['employee']->id)
        ->and(tpdStoredText($document))->toContain('CERT-OWN-EXPIRED')->not->toContain('CERT-OTHER');
});

it('refuses a HOD generating for a direct report: only the employee or HR produce the document', function (): void {
    $f = tpdFixture();
    $store = app(TrainingPassportDocumentStore::class);

    // The HOD can read the member's passport (team view), which is exactly
    // why the generator check has to be its own guard.
    expect(fn () => $store->generate($f['hod'], tpdSubject($f['tenantId'], (int) $f['company']->id, $f['member'])))
        ->toThrow(TrainingPassportDenied::class);
    expect(TrainingPassportDocument::query()->forCompany($f['tenantId'], (int) $f['company']->id)->count())->toBe(0)
        ->and(TrainingPassportDocumentAudit::query()->forCompany($f['tenantId'], (int) $f['company']->id)->count())->toBe(0);
});

it('lets HR generate for an employee listed in the HR queue and audits HR as the actor', function (): void {
    $f = tpdFixture();

    Livewire::actingAs($f['hr'])
        ->test(HrGovernanceIndex::class)
        ->assertSee('Training passports')
        ->assertSee('Passport Member')
        ->call('generatePassportPdf', (int) $f['member']->id)
        ->assertHasNoErrors()
        ->assertSeeHtml('data-passport-document-download=');

    $document = TrainingPassportDocument::query()->forCompany($f['tenantId'], (int) $f['company']->id)->sole();
    expect($document->employee_entity_id)->toBe((int) $f['member']->id)
        ->and($document->generated_by_user_id)->toBe((int) $f['hr']->id)
        ->and(tpdStoredText($document))->toContain('CERT-MEMBER')->not->toContain('CERT-OWN-EXPIRED');

    $audit = TrainingPassportDocumentAudit::query()->forCompany($f['tenantId'], (int) $f['company']->id)->sole();
    expect($audit->actor_user_id)->toBe((int) $f['hr']->id)
        ->and($audit->event_type)->toBe(TrainingPassportDocument::EVENT_GENERATED);
});

it('refuses an HR queue employee id that is not listed for the selected company', function (): void {
    $f = tpdFixture();

    Livewire::actingAs($f['hr'])
        ->test(HrGovernanceIndex::class)
        ->call('generatePassportPdf', (int) $f['siblingEmployee']->id)
        ->assertStatus(404);

    expect(TrainingPassportDocument::query()->withoutCompanyScope('test counts across companies')->count())->toBe(0);
});

it('serves the document to its employee as a PDF attachment and audits the download', function (): void {
    $f = tpdFixture();
    $document = app(TrainingPassportDocumentStore::class)
        ->generate($f['user'], tpdSubject($f['tenantId'], (int) $f['company']->id, $f['employee']));

    $response = tpdDownload($f['user'], (int) $document->id);
    $response->assertOk()
        ->assertHeader('Content-Type', 'application/pdf');
    expect($response->headers->get('Content-Disposition'))->toContain('attachment')
        ->and($response->streamedContent())->toContain('CERT-OWN-EXPIRED');

    $events = TrainingPassportDocumentAudit::query()
        ->forCompany($f['tenantId'], (int) $f['company']->id)
        ->where('document_id', $document->id)
        ->orderBy('id')
        ->pluck('event_type')
        ->all();
    expect($events)->toBe([TrainingPassportDocument::EVENT_GENERATED, TrainingPassportDocument::EVENT_DOWNLOADED]);
    expect(TrainingPassportDocumentAudit::query()->forCompany($f['tenantId'], (int) $f['company']->id)
        ->where('event_type', TrainingPassportDocument::EVENT_DOWNLOADED)->sole()->actor_user_id)->toBe((int) $f['user']->id);
});

it('refuses a second employee downloading the first employee document by id', function (): void {
    $f = tpdFixture();
    $document = app(TrainingPassportDocumentStore::class)
        ->generate($f['user'], tpdSubject($f['tenantId'], (int) $f['company']->id, $f['employee']));

    tpdDownload($f['otherUser'], (int) $document->id)->assertNotFound();

    expect(TrainingPassportDocumentAudit::query()->forCompany($f['tenantId'], (int) $f['company']->id)
        ->where('event_type', TrainingPassportDocument::EVENT_DOWNLOADED)->count())->toBe(0);
});

it('refuses HR of a sibling company downloading the document by id', function (): void {
    $f = tpdFixture();
    $document = app(TrainingPassportDocumentStore::class)
        ->generate($f['user'], tpdSubject($f['tenantId'], (int) $f['company']->id, $f['employee']));

    tpdDownload($f['siblingHr'], (int) $document->id)->assertNotFound();
});

it('serves the document to HR of the company', function (): void {
    $f = tpdFixture();
    $document = app(TrainingPassportDocumentStore::class)
        ->generate($f['user'], tpdSubject($f['tenantId'], (int) $f['company']->id, $f['employee']));

    tpdDownload($f['hr'], (int) $document->id)->assertOk()->assertHeader('Content-Type', 'application/pdf');
});

it('refuses a download once the retention window has passed', function (): void {
    $f = tpdFixture();
    Carbon::setTestNow('2026-09-07 10:30:00');
    $document = app(TrainingPassportDocumentStore::class)
        ->generate($f['user'], tpdSubject($f['tenantId'], (int) $f['company']->id, $f['employee']));

    Carbon::setTestNow('2026-10-07 10:29:59');
    tpdDownload($f['user'], (int) $document->id)->assertOk();

    Carbon::setTestNow('2026-10-07 10:30:00');
    tpdDownload($f['user'], (int) $document->id)->assertNotFound();
});

it('reuses the stored document when generated again on unchanged data the same day', function (): void {
    $f = tpdFixture();
    $store = app(TrainingPassportDocumentStore::class);
    $subject = tpdSubject($f['tenantId'], (int) $f['company']->id, $f['employee']);

    $first = $store->generate($f['user'], $subject);
    $second = $store->generate($f['hr'], $subject);

    expect($second->id)->toBe($first->id)
        ->and(TrainingPassportDocument::query()->forCompany($f['tenantId'], (int) $f['company']->id)->count())->toBe(1)
        ->and(TrainingPassportDocumentAudit::query()->forCompany($f['tenantId'], (int) $f['company']->id)->count())->toBe(1)
        ->and(MediaAsset::query()->count())->toBe(1);
});

it('purges expired documents: the bytes and asset go, the row and its audit stay', function (): void {
    $f = tpdFixture();
    Carbon::setTestNow('2026-09-07 10:30:00');
    $store = app(TrainingPassportDocumentStore::class);
    $expired = $store->generate($f['user'], tpdSubject($f['tenantId'], (int) $f['company']->id, $f['employee']));
    $asset = $expired->asset;
    Carbon::setTestNow('2026-10-01 10:30:00');
    $kept = $store->generate($f['otherUser'], tpdSubject($f['tenantId'], (int) $f['company']->id, $f['other']));

    Carbon::setTestNow('2026-10-08 00:00:00');
    test()->artisan('people:training-passport:purge', ['--tenant' => $f['tenantId']])
        ->expectsOutputToContain('Purged 1 expired')->assertSuccessful();

    expect($expired->fresh()->media_asset_id)->toBeNull()
        ->and(MediaAsset::query()->whereKey($asset->id)->exists())->toBeFalse()
        ->and(Storage::disk($asset->disk)->exists($asset->storage_key))->toBeFalse()
        ->and($kept->fresh()->media_asset_id)->not->toBeNull()
        ->and(TrainingPassportDocumentAudit::query()->forCompany($f['tenantId'], (int) $f['company']->id)
            ->where('document_id', $expired->id)->count())->toBe(1);
});

it('keeps audit rows append-only', function (): void {
    $f = tpdFixture();
    app(TrainingPassportDocumentStore::class)
        ->generate($f['user'], tpdSubject($f['tenantId'], (int) $f['company']->id, $f['employee']));
    $audit = TrainingPassportDocumentAudit::query()->forCompany($f['tenantId'], (int) $f['company']->id)->sole();

    expect(fn () => $audit->update(['event_type' => 'tampered']))->toThrow(TrainingPassportDenied::class)
        ->and(fn () => $audit->delete())->toThrow(TrainingPassportDenied::class);
});
