<?php

return [
    'items' => [
        [
            'id' => 'people.claim',
            'label' => 'Claims',
            'icon' => 'heroicon-o-receipt-percent',
            'parent' => 'people',
        ],
        [
            'id' => 'people.claim.my',
            'label' => 'My Claims',
            'icon' => 'heroicon-o-paper-airplane',
            'route' => 'people.claim.index',
            'permission' => 'people.claim.view',
            'parent' => 'people.claim',
        ],
        [
            'id' => 'people.claim.approvals',
            'label' => 'Approvals',
            'icon' => 'heroicon-o-check-badge',
            'route' => 'people.claim.approvals',
            'permission' => 'people.claim.approve',
            'parent' => 'people.claim',
        ],
        [
            'id' => 'people.claim.operations',
            'label' => 'Claim Operations',
            'icon' => 'heroicon-o-clipboard-document-check',
            'route' => 'people.claim.operations',
            'permission' => 'people.claim.manage',
            'parent' => 'people.claim',
        ],
        [
            'id' => 'people.claim.settings',
            'label' => 'Claim Settings',
            'icon' => 'heroicon-o-cog-6-tooth',
            'permission' => 'people.claim.manage',
            'parent' => 'people.claim',
        ],
        [
            'id' => 'people.claim.settings.categories',
            'label' => 'Categories',
            'icon' => 'heroicon-o-folder',
            'route' => 'people.claim.settings',
            'permission' => 'people.claim.manage',
            'parent' => 'people.claim.settings',
        ],
        [
            'id' => 'people.claim.settings.types',
            'label' => 'Claim Types',
            'icon' => 'heroicon-o-tag',
            'route' => 'people.claim.settings.types',
            'permission' => 'people.claim.manage',
            'parent' => 'people.claim.settings',
        ],
        [
            'id' => 'people.claim.settings.policies',
            'label' => 'Policies',
            'icon' => 'heroicon-o-document-text',
            'route' => 'people.claim.settings.policies',
            'permission' => 'people.claim.manage',
            'parent' => 'people.claim.settings',
        ],
        [
            'id' => 'people.claim.settings.assignments',
            'label' => 'Assignments',
            'icon' => 'heroicon-o-user-group',
            'route' => 'people.claim.settings.assignments',
            'permission' => 'people.claim.manage',
            'parent' => 'people.claim.settings',
        ],
        [
            'id' => 'people.claim.settings.contexts',
            'label' => 'Contexts',
            'icon' => 'heroicon-o-building-office-2',
            'route' => 'people.claim.settings.contexts',
            'permission' => 'people.claim.manage',
            'parent' => 'people.claim.settings',
        ],
    ],
];
