<?php

return [
    'items' => [
        [
            'id' => 'people.leave',
            'label' => 'Leave',
            'icon' => 'heroicon-o-calendar-days',
            'parent' => 'people',
        ],
        [
            'id' => 'people.leave.my',
            'label' => 'My Leave',
            'icon' => 'heroicon-o-paper-airplane',
            'route' => 'people.leave.index',
            'permission' => 'people.leave.view',
            'parent' => 'people.leave',
        ],
        [
            'id' => 'people.leave.approvals',
            'label' => 'Approvals',
            'icon' => 'heroicon-o-check-badge',
            'route' => 'people.leave.approvals',
            'permission' => 'people.leave.approve',
            'parent' => 'people.leave',
        ],
        [
            'id' => 'people.leave.settings',
            'label' => 'Leave Settings',
            'icon' => 'heroicon-o-cog-6-tooth',
            'permission' => 'people.leave.manage',
            'parent' => 'people.leave',
        ],
        [
            'id' => 'people.leave.settings.types',
            'label' => 'Leave Types',
            'icon' => 'heroicon-o-tag',
            'route' => 'people.leave.settings',
            'permission' => 'people.leave.manage',
            'parent' => 'people.leave.settings',
        ],
        [
            'id' => 'people.leave.settings.policies',
            'label' => 'Policies',
            'icon' => 'heroicon-o-document-text',
            'route' => 'people.leave.settings.policies',
            'permission' => 'people.leave.manage',
            'parent' => 'people.leave.settings',
        ],
        [
            'id' => 'people.leave.settings.assignments',
            'label' => 'Assignments',
            'icon' => 'heroicon-o-user-group',
            'route' => 'people.leave.settings.assignments',
            'permission' => 'people.leave.manage',
            'parent' => 'people.leave.settings',
        ],
        [
            'id' => 'people.leave.settings.balances',
            'label' => 'Balance Statement',
            'icon' => 'heroicon-o-chart-bar',
            'route' => 'people.leave.settings.balances',
            'permission' => 'people.leave.manage',
            'parent' => 'people.leave.settings',
        ],
        [
            'id' => 'people.leave.settings.adjustments',
            'label' => 'Adjustments',
            'icon' => 'heroicon-o-pencil-square',
            'route' => 'people.leave.settings.adjustments',
            'permission' => 'people.leave.manage',
            'parent' => 'people.leave.settings',
        ],
        [
            'id' => 'people.leave.settings.carry-forward',
            'label' => 'Carry-Forward',
            'icon' => 'heroicon-o-arrow-path',
            'route' => 'people.leave.settings.carry-forward',
            'permission' => 'people.leave.manage',
            'parent' => 'people.leave.settings',
        ],
    ],
];
